#version 450
layout(local_size_x = 64) in;
layout(binding = 0) buffer D { float d[]; };
layout(binding = 1) buffer O { float o[]; };
layout(push_constant) uniform P { float dscale; float sscale; float bias; uint passes; uint n; } p;
void main() {
  uint i = gl_GlobalInvocationID.x;
  if (i >= p.n) { return; }
  for (uint pass = 0u; pass < p.passes; ++pass) {
    d[i] = d[i] * p.dscale + exp(o[i]) * p.sscale + p.bias;
  }
}
